"""empty message

Revision ID: bd31dc4168e1
Revises: b6eb51473869
Create Date: 2018-07-22 19:11:40.172217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd31dc4168e1'
down_revision = 'b6eb51473869'
branch_labels = None
depends_on = None


data = [
    {
        'title': 'Gone with the Wind',
        'description': "Gone with the Wind is a novel by American writer Margaret Mitchell, first published in 1936. ",
        'img': 'https://wx3.sinaimg.cn/large/400f4ee7ly1ftiyq96oumj205107r41l.jpg'
    },
    {
        'title': 'On the road',
        'description': 'On the Road is a novel by American writer Jack Kerouac, based on the travels of'
                         ' Kerouac and his friends across the United States.',
        'img': 'https://ws1.sinaimg.cn/large/400f4ee7ly1ftiyvcdh1nj206y0arac9.jpg'
    },
    {
        'title': 'The Great Gatsby',
        'description': 'The Great Gatsby is a 1925 novel written by American author F. Scott Fitzgerald'
                         ' that follows a cast of characters living in the fictional town of West and East'
                         ' Egg on prosperous Long Island in the summer of 1922.',
        'img': 'https://ws4.sinaimg.cn/large/400f4ee7ly1ftiz2xuq7fj20940dv10z.jpg'
    }
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    book_table = op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    op.bulk_insert(book_table, data)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    op.drop_table('book')
    # ### end Alembic commands ###
